### ISSUE TITLE
Private Nachricht :D

### ISSUE THREAD

**Issue by MedjayB** [Velcorn/BV#3]
Hey Velcorn,
ich konnte keine andere Möglichkeit finden dich zu kontaktieren. Daher hier als Issue.
Zu erst mal danke für die BV Lösungen, die haben mir echt weiter geholfen.
Sorry wenn das dich nervt oder wenn ich gierig klinge, aber hast du auch die Lösungen für die Moodle Tests? 
Es ist mir fast peinlich zu fragen, aber es wäre eine sehr sehr große Hilfe :)

Beste Grüße

**Comment by Velcorn** [comment]
Sorry, ist jetzt wahrscheinlich etwas zu spät. Keine Ahnung, warum ich die Nachricht erst jetzt sehe. Es gab letztes Jahr ziemlich sicher keine Moodle Tests, sonst hätte ich die ebenfalls hier in der Repo. Falls es noch nicht zu spät ist oder du generell Lust hast, kannst du mir gerne die Tests zukommen lassen (Telegram: Velcorn, Discord: Velcorn#8956, Email auf Anfrage) und ich stell die bei Zeiten mit Lösungen hier rein.

In any case, viel Erfolg bei der Prüfung 😅
